### ISSUE TITLE
/app.php/rt doesn't work.

### ISSUE THREAD

**Issue by orthohincom** [Sajaki/RecentTopics#150]
### Expected Behavior
Should list recent topics on a stansalone page

### Actual Behavior
php error

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function paybas\recenttopics\controller\page_controller::__construct(), 4 passed and exactly 5 expected in ext/paybas/recenttopics/controller/page_controller.php:53 Stack trace:
> #0 [internal function]: paybas\recenttopics\controller\page_controller->__construct(Object(phpbb\config\db), Object(phpbb\controller\helper), Object(phpbb\language\language), Object(paybas\recenttopics\core\recenttopics))
> #1 vendor/symfony/dependency-injection/ContainerBuilder.php(1176): ReflectionClass->newInstanceArgs(Array)
> #2 vendor/symfony/dependency-injection/ContainerBuilder.php(634): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'paybas.recentto...')
> #3 in ext/paybas/recenttopics/controller/page_controller.php on line 53

### Steps to Reproduce the Problem

  1. install on fresh 3.3.7 forum
  2. activate extension
  3. forumroot/app.php/rt

### Specifications

  - phpbb version: 3.3.7
  - recenttopics version: 2.2.15

**Comment by avandenberghe** [comment]
Fixed in 3.0.0: the page controller has been rewritten under avathar/recenttopicsav.

**Comment by avandenberghe** [comment]
Fixed in 3.0.0 (commit 9552cc7): added guarded include of functions_display.php and fixed template path for the standalone /app.php/rt page.
